### ISSUE TITLE
What about control of the automatic transmission?

### ISSUE THREAD

**Issue by DmitryTgn** [PolySync/oscc#180]
I didn't find any information about switching the selector to position "D", "P", "R". Do you plan to implement control automatic transmission?

**Comment by k-cleary** [comment]
Hey Dmitry,

While this is definitely an interesting idea, the Kia Soul requires mechanical actuation of the gear shift to change gears. Since it doesn't support shift-by-wire we aren't able to actuate that on this vehicle purely electronically with OSCC. We have spent some time investigating a viable shift-robot, but currently have no plans to implement this on our immediate roadmap. It isn't a matter of technical feasibility. It's a matter of time and prioritization for the use cases we see most commonly.

You can still use OSCC while the car is in Park or Reverse. It works the way you'd expect. There may also be CAN messages from the vehicle's OBD-II CAN that report the state of the transmission, but we don't currently track them at this time.
 
Cheers,
Katie
