### ISSUE TITLE
Steering error when disconnect power

### ISSUE THREAD

**Issue by rg4444** [PolySync/oscc#202]
I got the error messages from car - yellow steering wheel and skid control icons in following conditions:
1. The OSCC is off the power, start engine (no errors), switch power - error lights goes on;
2. The engine is off, OSCC is on, switching on engine - no errors, enable controls etc;
3. When controls are enabled touching any - steer brake or accel disables control and steering fallback to normal mode without car errors;
4. When controls are enabled, switching off OSCC power disables controls and switches on steering error light - so steering is in emergency state - no actuation.
Any clues about reasons?
Any relations to this?: I use OBD cable with power switch - if the switch is ON  - whole OSCC is getting power from OBD2 connnector, so emergency switch doesn't operate. If switch is off I got more frequent car error messages.
And after 3+ trials car going to locked mode - so need to connect VCI and erase code to restore power steering.

**Comment by austinjmorlan** [comment]
That is expected behavior with the current hardware. OSCC must be powered before the vehicle is turned on. When the OSCC steering module is not powered, it is unable to pass the signal from the steering wheel to the EPAS causing the vehicle to think something is wrong. When the OSCC steering module is powered, it is able to pass the signal through and the vehicle detects nothing is wrong.
