### ISSUE TITLE
Kia Soul Petrol

### ISSUE THREAD

**Issue by ramizka** [PolySync/oscc#323]
Hi!

I would like to buy Kia Soul II, petrol. Should it have SPAS module, Automatic Park Assistant. Or we can use any Kia Soul? What exact specifications should car have to successfully use with Oscc?

**Comment by kenkeiter** [comment]
There are no specific requirements with regard to vehicle features; however, at PolySync we no longer support the Kia Soul because it requires significant modifications to the OEM braking system, which has reasonably serious safety implications. 

We recommend that you consider any of the Kia Niro variations.
